[package]
name = "dependsql"
version = "0.1.0"
edition = "2021"

[dependencies]
minijinja = "0.23.0"
regex = "1.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.3.2"
pyo3 = { version = "0.17.2", features = ["extension-module"] }
